[workspace]
authors = ["Régis Terrier <rterrier@apc.in2p3.fr>"]
channels = ["conda-forge", "bioconda"]
name = "my_project"
platforms = ["osx-arm64", "win-64", "osx-64", "linux-64"]
version = "0.1.0"

[tasks]
hello = 'echo "Hello, Pixi!"'
greet = { cmd = 'echo "Hello, {{ name }}!"', args = ["name"] }
start = { cmd = "greet::{{ name }}", args = ["name"], depends-on = ["hello", "greet"] }
greet-YOUR_NAME = { cmd = "greet", args = ["YOUR_NAME"], depends-on = ["greet"] }

[dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
python = ">=3.13.5,<3.14"
scipy = "==1.15.1"
numpy = ">=2.3.2,<3"
fastqc = ">=0.12.1,<0.13"
pandas = ">=2.3.2,<3"

[feature.test.pypi-dependencies]
pytest = { git = "https://github.com/pytest-dev/pytest.git", tag = "8.3.1" }

[feature.format.dependencies]
ruff = "*"

[environments]
test = ["test"]
format = { features = ["format"], no-default-feature = true }
